### ISSUE TITLE
Jittering Inputs

### ISSUE THREAD

**Issue by PortablePanda** [steve1316/granblue-automation-android#25]
Hello! When using this on my mobile device, it seems as if the bot constantly performs meaningless taps near the center of the screen, which cause it to shift up and down and cause delays.

**Comment by steve1316** [comment]
Without a video, I cant be sure but I assume you are talking about the up/down swipes near the top of the screen. They exist because the bot relies on ImageReader to get the contents of the screen. Unfortunately, it comes with the downside of ImageReader not refreshing with a brand new image unless something on the screen changes. 

Since GBF is completely static most of the time except for animations and during Combat, the bot will "move" the screen up and down to force a change for ImageReader to generate a new image.

If it is not swipes, then a video shoecasing the issue along with the associated log would help.

**Comment by PortablePanda** [comment]
Here you go! Sorry for the extreme and ugly redaction, I just thought it would be best to hide any potentially identifying information. Also, this was mirrored directly from my actual phone.


https://user-images.githubusercontent.com/82384904/182458808-0792d24c-8588-41b9-8dde-8157422bc445.mp4


[log @ 2022-08-02 14:48:34.txt](https://github.com/steve1316/granblue-automation-android/files/9245094/log.%40.2022-08-02.14.48.34.txt)

**Comment by steve1316** [comment]
Yeah, no worries about the redaction!

At 0:25, 0:46, and 2:08 of the video for example, they all match the behavior that I mentioned in the previous comment. Although it is fair to assume that the bot was peforming weirdly haha.

You can experiment with the Adjustments page with options like reducing General Image Searching from 5 to 3 for example to speed up the bot by a fair bit.

Also, in my personal experience, I would place the floating overlay button to the bottom far left corner or anywhere at the bottom of the SkyLeap UI to avoid the button obscuring something ingame.

**Comment by PortablePanda** [comment]
It seems like reducing the image searching sped things up a fair bit, thank you!
